### ISSUE TITLE
Summoning Keywords

### ISSUE THREAD

**Issue by sharkfan1a** [isitLoVe/RaidSummon#11]
First of all, the addon is beastmode. The custom keywords for summoning is dope.

However, after setting up the custom summoning keywords, logging out and logging back in reverts it to default.

This is happening with all the locks that have started using the custom keyword functions.

**Comment by isitLoVe** [comment]
Hi, thanks for the report. Are you deleting all of the 3 default keywords and add new ones? What new keyword(s) are you using.
I need more info to reproduce.

**Comment by sharkfan1a** [comment]
I am removing all the old keywords first and adding only ^1$ as a usable keyword for summoning.

Logging to the character select screen then logging back in, the 3 defaults are back, as well as the ^1$ I added before.

**Comment by isitLoVe** [comment]
Confirmed as a bug

**Comment by sharkfan1a** [comment]
I just wanted to check back in on this. My guild is pretty dedicated to dominating world bosses and this tool is making this easier, in general. The fix would of course make it idea.

Another option, if you're looking for one, would be to have the tool come with no keywords configured by default. This way, it's up to the user to define only the keywords they want.

**Comment by isitLoVe** [comment]
fixed in 3.3.1
