### ISSUE TITLE
Raidsummon Queue

### ISSUE THREAD

**Issue by sharkfan1a** [isitLoVe/RaidSummon#13]
This is not a bug report but a request for a feature or two to help me streamline the summoning process in my raid groups.

The first suggestion would be to have a customizable font size for the queue. One of my guildmates is pretty blind so being able to scale the font would be very useful for him, and for me since I'm getting old.

Second suggestion would be to be able to resize the summon queue window. We are using the addon for world boss summons, so a 3 person summoning team quickly becomes a 37 person summoning queue, and since there is no priority sorting I would like to be able to pick who I need to be there with me from the entire queue. I think my favorite way to do this would be to have the size of the window adjust itself with the size of the queue, if such a thing is possible.

That leads me to suggestion number 3, which would be list sorting. In Decursive I am able to sort by group, class or role. I would like to be able to sort the list in the same manner. At the very least sort by class so I can pick a tank, or healer, or another summoner and get things organized more efficiently.

Thank you for your time! :)

**Comment by isitLoVe** [comment]
Hi,
thanks for the suggestion. When i have time again the following should be implemented:

- Custom font and font size in options (fonts with libsharedmedia)
- resize as suggested in #14 
- sorting feature by class or name (currently only warlocks have prio)

**Comment by sharkfan1a** [comment]
Thanks. Been using a custom job from a guildmate but would love to see these in the official release.

**Comment by isitLoVe** [comment]
cleanup
