### ISSUE TITLE
Addon will add people to the queue without keywords

### ISSUE THREAD

**Issue by Voidheart90** [isitLoVe/RaidSummon#16]
**Describe the bug**
Inside instance / raid if a person talks in raid chat, sometimes they don't have to say anything. It will add them even myself to the queue.. using /rs clear will clear it but it will continue. I've uninstalled / deleted the saved variables and /reloadui and still occurs

**Screenshot or LUA error paste**
https://imgur.com/a/gLjEkkl

**To Reproduce**
1. Raid instance, 40 people (happens in BWL / MC, haven't done much of ZG to find out)
2. when people communicate in /ra chat

**Expected behavior**
Not capturing keywords, seems to add everyone in the queue list

**Additional context**

**Comment by Voidheart90** [comment]
Last night I did molten core and I didn't have the problem replicated, I'm curious the Add-on communication between older and newer versions is causing the issue? Maybe you could place a versioning check to not communicate with older versions or compatibility support?

This right now is a hunch because we didn't have a full 40 last night

**Comment by isitLoVe** [comment]
Check your keywords list if there is something in it. It could also be another warlock adding ppl via the target frame (right click menu).

**Comment by Voidheart90** [comment]
Keywords list was at default, nothing new. Even erased saved variables and reinstalled the add-on, still had the same problem

**Comment by ecnu-zz** [comment]
Any fix to this issue? Still happening in raid.

**Comment by isitLoVe** [comment]
cleanup
