### ISSUE TITLE
Non warlock to monitor the summons

### ISSUE THREAD

**Issue by Thardene** [isitLoVe/RaidSummon#17]
**Additional context**
Is there a way for a non warlock to monitor who has requested a summon ? When in a raid with warlocks with the addon (I have obviously the addon installed ) they can normally see who has requested a summon , but I can't ( I m a druid)  . /rs toggle shows the window as usual and doing a /rs list I can see who has requested a summon , but not on the main window.

**Comment by isitLoVe** [comment]
Hi,
i will add an option to show the frame even as another class. However i have no time to to do currently.
If you know Lua you can just delete line 181, 183, 469, 544 as a quick fix.

**Comment by isitLoVe** [comment]
cleanup
