### ISSUE TITLE
How do I get it to respond to multi word phrases ONLY?

### ISSUE THREAD

**Issue by lvangh** [isitLoVe/RaidSummon#25]
We have summoners at several locations and don't want the addon to pick up cross zone requests. 

We have people type
`123`zg`

or `123 dm` 

Etc. But even if all keywords are removed it's still picking up other zones. 

I've tried adding the registered keywords
`^123 zg$`
`^123 $ zg$`
`^"123 zg"`

etc but it's still picking up other things. I have all words removed but "123" is still being picked up.

**Comment by isitLoVe** [comment]
First you should reset the keywords to default (via the profiles tab), then remove the 3 default keywords.  
You can add your keywords then, eg. `^123 zg$` (will match the exact phrase)

**Comment by lvangh** [comment]
Unfortunately it's still picking up other phrases. Here is a screenshot of it happening despite the KW list only having 2 items, 
![image](https://user-images.githubusercontent.com/19690096/84615558-35350180-ae7e-11ea-8ff6-ff0f9f5a2eef.png)

**Comment by isitLoVe** [comment]
I see you are in a raid grp with more warlocks, maybe some other warlock still has 123 in the keyword list. The summon reuquest is then synced to you.
