### ISSUE TITLE
The player clicked in the queue is not automatically targeted.

### ISSUE THREAD

**Issue by Chalos-Atiesh** [isitLoVe/RaidSummon#29]
**Describe the Bug**
If I have a target and click a different name then my target remains the same and I summon my current target. It would be super nice if the addon targeted the name I clicked in the queue and then summoned them.

**Screenshot or LUA Error Paste**
N/A

**To Reproduce**
1. Enter a raid with 3+ people.
2. Toggle RaidSummon display on with /rs
3. Have somebody queue for a summon. Let's say their name is XYZ.
4. Target a _different_ player. Let's say their name is ABC.
5. Click the name XYZ in the queue.

**Expected Behavior**
XYZ should be targeted and then summoned.

**Actual Behavior**
ABC is summoned and an error is printed saying that the expected and targeted names to not match.

**Additional context**
None.

**Comment by isitLoVe** [comment]
Due to the Blizzard API with Ritual of Summoning, we cannot "target and summon" a player with one click (like spell targeting someone or mouseover macros), you have to target the player with one click, and summon (cast) him with a second click.  
Maybe someone can fix this or has a workaround.

**Comment by Chalos-Atiesh** [comment]
That seems reasonable to me. Have the player targeted on the first click (and not removed from the list) and then summoned on the second click. Then they are removed from the list after the second click.

Or, alternatively, have them targeted with modifier+click and then summoned with click.

My main complaint with having them not targeted with the /rs frame is that I still have to hunt through the raid frames to find their name.
