### ISSUE TITLE
Logs me out of Wow Classic when I try to RS remove someone

### ISSUE THREAD

**Issue by Scorpita** [isitLoVe/RaidSummon#30]
Sorry could not grab a screenshot as I was immediately logged out of the game.  Not sure if this happens for others or is some sort of conflict with my other addons but hopefully when you try it you will experience the same.  If not let me know if there is a specific log file to send you.

How to create:  in a raid for BWL, at the command line typed  "/rs remove" and system returned me to he wow logon screen.
Logged back in and repeated thinking it was just a one-time glitch - same thing:  exited wow and returned me to the logon screen.

**Comment by isitLoVe** [comment]
Confirmed bug, i tried it in BWL, got logged out too. Need to have a look
