### ISSUE TITLE
[Feature Request] Modify Summoning List Priority (Ex: Remove Warlock Prio)

### ISSUE THREAD

**Issue by boktai1000** [isitLoVe/RaidSummon#33]
Hello there!

Simply requesting the ability to be able to change or remove certain priority from the summon queue / list.

As you've mentioned and I've picked up from comments, Warlocks currently have priority in the summoning list.

One of the use cases we are using this Addon for is for selling summons and people typing "123" when they're ready, but Warlocks that are purchasing summons jump the queue as a result unfortunately when we want to go chronologically. I understand why from a "Raid Summon" POV but from a summon-as-a-service POV it breaks things a bit.

If you happen to know what lines to modify in the meantime to remove this I would be happy to make the modification on my end as a result, but I figured more customization or the ability to change priority depending on user preference would be a good thing as well 👍 

Cheers!

**Comment by isitLoVe** [comment]
Will take a look at it, currently the list is not sorted by anything (just warlocks are on top).

**Comment by dieck** [comment]
I would like to second the idea of going chronologically. 
(Thus with warlocks on top being configurable enabled/disabled - we like that :))

This would not only be beneficial for selling ports as boktai1000 mentioned, but also for better coordination within the same raid.
We tend to do chains of ports for Buff optimization, from DM Tribute to Songflower to ZG buff to Dragonbuff to AQ instance, or something like that. We noticed that the order in which people are ported are not deterministic, or at least not in a way we can determine - except Warlocks on top, of course.
But this would be nice to know, e.g. if you are about 30th in line, you could log off for 7-8min until it's your turn.

**Comment by isitLoVe** [comment]
cleanup
