### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by SunNova67** [isitLoVe/RaidSummon#34]
Requesting option for keyword exact match instead of string.find in text being searched for keywords, this would stop matches from folks typing instructions to raid members for summons.

**Comment by isitLoVe** [comment]
You can do exact phrases via regex:
^port$ will only match port
^please port me$ will match the exact phrase

**Comment by SunNova67** [comment]
got it, thank you, somehow I had used ^s1&, didn't even notice I had & instead of $.
