### ISSUE TITLE
WTB new 123 entries added to the bottom + autoremove based on COMBAT_LOG_EVENT_UNFILTERED

### ISSUE THREAD

**Issue by ghost** [isitLoVe/RaidSummon#41]
Took me a while and a full raid writing 123 to see that new entries are added to the top. Which is the most logic spot to choose who is next to summon. Meaning the oldest 123 will get summoned last.

There are also lots of ppl not using summoning addons couse they are all bugged too much to bother with. Would then be nice if this one can sniff up manual and completed summoning casts via COMBAT_LOG_EVENT_UNFILTERED

**Comment by isitLoVe** [comment]
cleanup
