### ISSUE TITLE
[Feature Request]Add Parsing for Zone

### ISSUE THREAD

**Issue by sdensberger** [isitLoVe/RaidSummon#42]
Add parsing functionality so that when someone sends a chat message for a summon they can also request where they want to be summoned to. This would help for a raid group that is handling summons to DMT, then DMF, then SFS, etc. For example, if player LeeroyJenkins wanted a summon to DMT he would send the following message:

summon dmt

In the summoning frame it'd show:

LeeroyJenkins - dmt

This would help the respective summoning alt know who they should summon next.

**Comment by isitLoVe** [comment]
maybe add this feature if we get to SoD endgame
