### ISSUE TITLE
Summoning List Cleared When New Players Join Raid

### ISSUE THREAD

**Issue by insano70** [isitLoVe/RaidSummon#44]
**Describe the bug**
I often am the solo summoner for my entire raid, all 40 people, using a summoning team. I'll start the raid and then invite people as they log in. In almost every raid a person will get invited and then the entire summoning queue list will clear to empty. It *seems* to maybe be people with the RaidSummon addon installed. It's almost like they have a queue of zero and I have a queue of X players and their queue overwrites mine. 

**Screenshot or LUA error paste**
I dont have a screenshot, it would just be an empty summoning window. 

**To Reproduce**
1. Set up 3 person summon group
2. Multiple people request summon
3. New person added to raid
4. Summoning queue is now empty but summoning window remains open

**Expected behavior**
The expected behavior is that the queue in place remains in place until everyone in it is remove either by getting summoned or manually. 

**Additional context**
I have experienced this on 3 separate computers, 2 macs and 1 PC. Each computer gets wiped periodically and a fresh OS install and it happens even on a fresh install.

**Comment by isitLoVe** [comment]
cleanup
