### ISSUE TITLE
Raid summon does not handle mixed servers properly 

### ISSUE THREAD

**Issue by Yojione** [isitLoVe/RaidSummon#49]
I am Mirage Raceway server - classic era, but it seems to have been consolidated with other servers - so people from "Netherguardkeep" or "PyrewoodViallage" are all mixed with me in my guild.

The problem is that people appear in raidsummon as
xxxxx-Netherguardkeep    (for example) 
and if I click on their name... and then right click to summon
it does do the summon, but I get an error saying that the name does not match who I trying to summon (that is the gist of message... I cant recall exactly - let me know if you need a screen shot or the exact text)
Anyway - it means it does not do the announce to the person.. or the announce in raid chat. 

Cant recall if it removes them from summon list correctly... 
And cannot verify if it removes  them from other locks summon lists (I am only lock in guild using ... at the moment - I am working on converting them ;).. and it would help if it all worked)

Anyway - let me know if you th9ink I talking rubbish and need more info/evidence or have questions.

Cheers and thanks for the addon.. its very nice (When I can get all locks to use)

**Comment by isitLoVe** [comment]
sorry, I only play SoD and cant fix thix
