### ISSUE TITLE
Does not work in party - feature req.

### ISSUE THREAD

**Issue by lvangh** [isitLoVe/RaidSummon#5]
**Describe the bug**
** EDIT * sorry I am mistaken, it did only work in /Raid on 1.12 confirmed on pserv.

**Screenshot or LUA error paste**
No error.

**To Reproduce**
1. Be in a regular party 
2. have someone type 123
3. name does not appear.
4. Convert to raid and it works.

**Expected behavior**
Usable in party mode.

**Comment by isitLoVe** [comment]
On it but will take some time

**Comment by lvangh** [comment]
Thank you for adding this! 💪

**Comment by isitLoVe** [comment]
Its raid summon not party summon
