### ISSUE TITLE
Addon fails to load.

### ISSUE THREAD

**Issue by VTSVirus** [isitLoVe/RaidSummon#50]
**Describe the bug**
Never Loads receives a crash message.

**Screenshot or LUA error paste**
Message: [string "*RaidSummon.xml:7_OnLoad"]:2: 
attempt to call method 'SetBackdropColor' (a nil value)
Time: Mon Dec 18 20:35:27 2023
Count: 10
Stack: [string "*RaidSummon.xml:7_OnLoad"]:2: attempt to call method 'SetBackdropColor' (a nil value)
[string "*RaidSummon.xml:7_OnLoad"]:2: in function <[string "*RaidSummon.xml:7_OnLoad"]:1>

Locals: self = RaidSummon_NameList10 {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = RaidSummon_NameList10 {
 0 = <userdata>
}
(*temporary) = 0.800000
(*temporary) = 0.800000
(*temporary) = 0.800000
(*temporary) = 0
(*temporary) = "attempt to call method 'SetBackdropColor' (a nil value)"

**To Reproduce**
Install addon
Login to SoD

**Expected behavior**
The addon to load.

**Additional context**

**Comment by isitLoVe** [comment]
New Version is out, get it on curseforge
https://legacy.curseforge.com/wow/addons/raidsummon
