### ISSUE TITLE
Create/set/choose 1 keyword for chat addition to summon list

### ISSUE THREAD

**Issue by magiclemur** [isitLoVe/RaidSummon#8]
Being able to create a keyword for raid members to type in chat for being added to the summon list would be awesome. Or even being able to select 1 of the keywords already active to be the only one that adds to my summon list.

**Comment by isitLoVe** [comment]
Should be doable, but as always takes some time.

**Comment by magiclemur** [comment]
Awesome! I love the addon and am pushing for it on all the locks in my guild! Makes summoning a raid doable

**Comment by isitLoVe** [comment]
Resolved in version 3.3.0
